schema_version = "1.0.0"

id = "rizom_bridge"
version = "1.0.0"
type = "add-on"

maintainer = "MaelPERON"
original_author = "Renaux Alexandre (@sky-ark)"
name = "RizomBridge"
tagline = "Bridge between Blender and RizomUV for efficient UV unwrapping"
description = "Blender addon to fasten the UV unwrapping and packing through RizomUV back to Blender."

blender_version_min = "4.2.1"

license = [
  "SPDX:GPL-3.0-or-later",
]

permissions = []

[resources]
homepage = "https://github.com/MaelPERON/RizomBridge-Blender"
bug_tracker = "https://github.com/MaelPERON/RizomBridge-Blender/issues"
source_code = "https://github.com/MaelPERON/RizomBridge-Blender"

tags = [
    "Import-Export",
    "UV",
    "RizomUV",
    "3D",
]